export default {

    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_COMPLETE: "LOGIN_COMPLETE",
    LOGIN_FAIL: "LOGIN_FAIL",

    SIGN_UP_REQUEST: "SIGN_UP_REQUEST",
    SIGN_UP_COMPLETE: "SIGN_UP_COMPLETE",
    SIGN_UP_FAIL: "SIGN_UP_FAIL"
}